### PR TITLE
Enable Unit Tests in Travis-CI Test Builds/Increase Go version used in Travis-CI to 1.8/1.9

### PR DESCRIPTION
**Pull request by spencerlievens**

### CODE REVIEW

**Comment by alexbosworth** [comment]
utACK

**Comment by spencerlievens** [comment]
Fully functional ;)

```
$ cd $GOPATH/src/github.com/bitgo/prova/blockchain

$ go test -v
=== RUN   TestErrNotInMainChain
--- PASS: TestErrNotInMainChain (0.00s)
=== RUN   TestStxoSerialization
=== RUN   TestStxoDecodeErrors
=== RUN   TestSpendJournalSerialization
=== RUN   TestSpendJournalErrors
=== RUN   TestUtxoSerialization
=== RUN   TestUtxoEntryHeaderCodeErrors
=== RUN   TestUtxoEntryDeserializeErrors
=== RUN   TestBestChainStateSerialization
=== RUN   TestKeySetSerialization
=== RUN   TestBestChainStateDeserializeErrors
=== RUN   TestVLQ
=== RUN   TestScriptCompression
=== RUN   TestScriptCompressionErrors
=== RUN   TestAmountCompression
=== RUN   TestCompressedTxOut
=== RUN   TestTxOutCompressionErrors
=== RUN   TestIsGenerationShareRateLimited
--- PASS: TestIsGenerationShareRateLimited (0.00s)
=== RUN   TestHaveBlock
--- PASS: TestHaveBlock (0.01s)
=== RUN   TestBigToCompact
--- PASS: TestBigToCompact (0.00s)
=== RUN   TestCompactToBig
--- PASS: TestCompactToBig (0.00s)
=== RUN   TestCalcWork
--- PASS: TestCalcWork (0.00s)
=== RUN   TestErrorCodeStringer
--- PASS: TestErrorCodeStringer (0.00s)
	error_test.go:66: Running 44 tests
=== RUN   TestRuleError
--- PASS: TestRuleError (0.00s)
	error_test.go:93: Running 2 tests
=== RUN   TestFullBlocks
--- PASS: TestFullBlocks (0.20s)
	fullblocks_test.go:47: Testing block bm0 (hash 00d36527996e8432e07ce345c149ab6132a247dede7bea16844102a466542901, height 1)
	fullblocks_test.go:47: Testing block bm1 (hash 0123605769baafd47a90829caffcd8ceb8f5b3612927be85c15701cebaeb790d, height 2)
	fullblocks_test.go:47: Testing block bm2 (hash 03a1b84cb129c44c5020cacdcbc13ae4380da5274ba24237ebc486a01425e353, height 3)
	fullblocks_test.go:47: Testing block bm3 (hash 0e1ad338185edeee0a008cf3c34528893959247e5aa115b0da97db5d861f227e, height 4)
	fullblocks_test.go:47: Testing block bm4 (hash 04eb1907b41b368e14a5595052d69c3ad49d7b3dfc5336511eda065f47648563, height 5)
	fullblocks_test.go:47: Testing block bm5 (hash 0b94d3cf25f37ecdde0809fd9b5f0848aa853b3a9354c904ad9ba8db8f8259b3, height 6)
	fullblocks_test.go:47: Testing block bm6 (hash 024fcd061cbb75a78b68ed00c198a26903107546a68572b89667fa5de41f5ed8, height 7)
	fullblocks_test.go:47: Testing block bm7 (hash 0cec93ac9a8b4f0c332b6ffe09afd037e4733d6da883b22684efd9da64f178f9, height 8)
	fullblocks_test.go:47: Testing block bm8 (hash 05243e6b02fb23d106104c71404ae12aadcf0735e772841506dcfbadc644437b, height 9)
	fullblocks_test.go:47: Testing block bm9 (hash 0d4c156409add5a84fd39291ed4ab753d98ffe7a1e71fe181575f2bd248492e7, height 10)
	fullblocks_test.go:47: Testing block bm10 (hash 0119a7978f568d0e5d455309c77f86ae72070a4a6b95fe8cedac09d46569da49, height 11)
	fullblocks_test.go:47: Testing block bm11 (hash 0d2539e15fb6fc322a962af6a5e31f864ac0f6c5d4782afdf3fccda7b7d4e4a8, height 12)
	fullblocks_test.go:47: Testing block bm12 (hash 07812f34c315f06b40d5dd1f3a6b48e42bfeb0026ea878497c9222fcd5adc2ca, height 13)
	fullblocks_test.go:47: Testing block bm13 (hash 0da8d5de8096eaccda20f4ebf6f00ceaddc5517a99b0b743f7e565373da5ae52, height 14)
	fullblocks_test.go:47: Testing block bm14 (hash 0c864b24b1bd681ae10e5db82c887fe5c784b22d95eaebd990c74a0376c42250, height 15)
	fullblocks_test.go:47: Testing block bm15 (hash 09a6ae328d4aaf0ca6c5bc5b4934f767c23ca7df43a5c3ce12e5970c232c9da1, height 16)
	fullblocks_test.go:47: Testing block bm16 (hash 0a0cf783b3cc9093c9d46a6444df6b1741cf383c35fd630e7b6cc0e90819bc1e, height 17)
	fullblocks_test.go:47: Testing block bm17 (hash 08a7e5fc4ab1356a6990e4cc87a64e28ce1d976adf8d72216cfde950386514c3, height 18)
	fullblocks_test.go:47: Testing block bm18 (hash 09731c7b8a5e2a8a8cde5e999ea2d080df1236bbe12df7b8c0819e18dc90295d, height 19)
	fullblocks_test.go:47: Testing block bm19 (hash 08df0f411c6f12061399f5050841c5546158292e502f3749ca353fb9d7aee233, height 20)
	fullblocks_test.go:47: Testing block bm20 (hash 0987543f80c9edde0739998e867f7552399ee8751d616681a14f8157d197be7c, height 21)
	fullblocks_test.go:47: Testing block bm21 (hash 07c2888979cb6a23aa8dcca7c3b092f20b2da7d40e94f9be26dc3a2f6c99d072, height 22)
	fullblocks_test.go:47: Testing block bm22 (hash 0a97d93daa9f7a001a1490e638dc396c03526d79de06c78a53da7846a4193055, height 23)
	fullblocks_test.go:47: Testing block bm23 (hash 075537c37c39b28e73dcdc203cc07c06a630172b204b510a5f1df077fac70398, height 24)
	fullblocks_test.go:47: Testing block bm24 (hash 09a0c52698e156d09d800fd34181c8188d2aba4957790e0883c4ab4fae9012f3, height 25)
	fullblocks_test.go:47: Testing block bm25 (hash 0a76ff5d794eab119bee71bc6c663e4eba645f93c3377a51c3401811b5c4422a, height 26)
	fullblocks_test.go:47: Testing block bm26 (hash 029b867016475a544a81debd4a10ba72486f23d6a1bb870a02f41fed9116a56e, height 27)
	fullblocks_test.go:47: Testing block bm27 (hash 063d65624aad105a487283fe9cc8d0b127ee8819c1ef8c08243ae87ded887fbf, height 28)
	fullblocks_test.go:47: Testing block bm28 (hash 011dd15f54ade7faa373260f7319c79d4f52de9f179180edeef3a4e4d231d9e0, height 29)
	fullblocks_test.go:47: Testing block bm29 (hash 0df657d85c4209b34f1fe5016d649f8fcb7a779b1dc54a21a1179fd7a44c8e8f, height 30)
	fullblocks_test.go:47: Testing block bm30 (hash 01511df81ee15acb012de8d99be0f9bcd0f67b3bb987137145469f6e7355c9f3, height 31)
	fullblocks_test.go:47: Testing block bm31 (hash 045fc81a711e479f7adbbb0188e82875f7e67fb71a0a0c869090e8f95a36a1d7, height 32)
	fullblocks_test.go:47: Testing block bm32 (hash 0e306003e4d21cb876bd0a7b45828642d1251d0d0ba3449c39ce7d505b70b1cd, height 33)
	fullblocks_test.go:47: Testing block bm33 (hash 0329e7517da962eea7003ca3c5a45b28747ec8ab709b746053790519130ad21c, height 34)
	fullblocks_test.go:47: Testing block bm34 (hash 03e1b060a98abd0f9e26096a1f566ed34176dade06375e7aef3b5ae8823ef157, height 35)
	fullblocks_test.go:47: Testing block bm35 (hash 030b8660daa70732a8f3901015db0fb76b81c464b790b51c3f973d6e14598521, height 36)
	fullblocks_test.go:47: Testing block bm36 (hash 022f6681a5e24bbaa2b33f68f53338dc7ba7a36fd3177a2b9bf1c83dd8e7254f, height 37)
	fullblocks_test.go:47: Testing block bm37 (hash 039873ed1f3f082ff4ee187a75f410f9fe0da9aa22ebc668c2078cd22efad6bb, height 38)
	fullblocks_test.go:47: Testing block bm38 (hash 03a6d9818748053e4fbd7553ea53047df4f1cb3f62d41976aa74dec1711a8772, height 39)
	fullblocks_test.go:47: Testing block bm39 (hash 0843f7373e889b9adc918fc8b0f7ece38ea2265a45fc6b17cf6341d7f952defd, height 40)
	fullblocks_test.go:47: Testing block bm40 (hash 0e74b3f5de77667e6ae0af1ac8930671c94f4047b9db7c36cc0dca18d416641f, height 41)
	fullblocks_test.go:47: Testing block bm41 (hash 017b14fbd996b20a0b1ad35003b4fa8e4dbf934076a22c6485d14bbc0d681c00, height 42)
	fullblocks_test.go:47: Testing block bm42 (hash 0265d412f28beee13e6f7e1c60dfa7761500eae3b0841176fad5496f8141e5bf, height 43)
	fullblocks_test.go:47: Testing block bm43 (hash 0c587dff56f0780ce5375bce28fdbdcb7604bc452622e6c89a41ff6de34c3c09, height 44)
	fullblocks_test.go:47: Testing block bm44 (hash 029e7b89f89aedb3d641eaa9a5af4343687c92a717a71b3a8e174e75153287a5, height 45)
	fullblocks_test.go:47: Testing block bm45 (hash 0838aa132b72ca0cd87674a2ef86d7bcbe724d6f6cee30b34bc7daf8194385a4, height 46)
	fullblocks_test.go:47: Testing block bm46 (hash 006ba0fad9d513c9be290bb7d4f0bc554004aa2e510616ad4795a1c43d90fa34, height 47)
	fullblocks_test.go:47: Testing block bm47 (hash 00c139d2b35fa1b482bfc66bbc66c364b52da3c3ea61f96db362505fb05c0fa2, height 48)
	fullblocks_test.go:47: Testing block bm48 (hash 088613cc49406d4ae3633a272bda68dd042050184d5238f665b68a09ac6d710c, height 49)
	fullblocks_test.go:47: Testing block bm49 (hash 067971c46049a809fa80aa6c71d19e32ac7d3d49f957d8d9ee80a1e409a2a47d, height 50)
	fullblocks_test.go:47: Testing block bm50 (hash 0c3f6b4aa01981860e7d6709833981eff400935d7685b0b804c65968dfc187f6, height 51)
	fullblocks_test.go:47: Testing block bm51 (hash 02ef08ac547eb999eff98fe40a1b6e751d0274cfe4deeddd659e389cf603559e, height 52)
	fullblocks_test.go:47: Testing block bm52 (hash 0b62eec4640fbdc9c70c13c0a7f211cb8c320b5dd4f441e53e622309892bad27, height 53)
	fullblocks_test.go:47: Testing block bm53 (hash 0efd36fddeed699ccd942cb3fdfe81a0b538f88e81c4a1ec009dfddafae351bd, height 54)
	fullblocks_test.go:47: Testing block bm54 (hash 072d124a2ea9ce9fedcbe584f0544e12ec62f5f325b33ee48474adef93f0115a, height 55)
	fullblocks_test.go:47: Testing block bm55 (hash 04915beb7aef741f7481572334f24255f93ce6d5bad260c7eb98c65273a50ef4, height 56)
	fullblocks_test.go:47: Testing block bm56 (hash 06ba88136989bbe650d1c1b0ce15f639420233f02344f515067e8f3096dbd067, height 57)
	fullblocks_test.go:47: Testing block bm57 (hash 0c4375cf4a0ac15bff02e088acb1d21fe11e44dfc9ead543a4a1bd446ee097a8, height 58)
	fullblocks_test.go:47: Testing block bm58 (hash 07ee41f9809fdcd48305148f9fd81a47c4db419a2a21ef49124bf685fafb643c, height 59)
	fullblocks_test.go:47: Testing block bm59 (hash 067fd72be03b663caee3803c67b67c9117d1b2b1532af8d7aafa412bef73f2e9, height 60)
	fullblocks_test.go:47: Testing block bm60 (hash 0a850c5a786a15049e6524c576d743da4a7e4976432ac696a8163d113a453a27, height 61)
	fullblocks_test.go:47: Testing block bm61 (hash 093884d894173e750e098194a878d591e371871f473e810f08d9954d788c52cf, height 62)
	fullblocks_test.go:47: Testing block bm62 (hash 05760d8670c7db00966845d894599cc92b8a39eae18e270323d13e5022b8ce6c, height 63)
	fullblocks_test.go:47: Testing block bm63 (hash 0704256f8232646cc5e85df86a415c80cfab1c875b25367954e2172baa52f13c, height 64)
	fullblocks_test.go:47: Testing block bm64 (hash 02739daa89000833be8c3e368d2e1f01778be2fecbd3a27834f880eab17f08a9, height 65)
	fullblocks_test.go:47: Testing block bm65 (hash 092642f3117858b617f102286eee3420d1af57a83d463c297ceb7a63f11f8dbf, height 66)
	fullblocks_test.go:47: Testing block bm66 (hash 0a64fb79a75fcfb44a5ff0869b566a951f6f81eff9052ad55bf309715455b85c, height 67)
	fullblocks_test.go:47: Testing block bm67 (hash 09bc0dc32b783e75d4a92a0b477c951eef9ee7bb45427fddf9116cc0fa231f74, height 68)
	fullblocks_test.go:47: Testing block bm68 (hash 02099d66de50d1ffadb779aa83b6f2312f970b7bb55109f55bc4c3c19b54c284, height 69)
	fullblocks_test.go:47: Testing block bm69 (hash 07b56a9e6353f642ed103e644328615567a02b1866f4d2f9b44372e06e5aca0b, height 70)
	fullblocks_test.go:47: Testing block bm70 (hash 014bde21efbed6f6b8339138bd709f1fcc9a1810ca607476011daa770a1dbb5d, height 71)
	fullblocks_test.go:47: Testing block bm71 (hash 091b07cdbd781b0f0f8855444bfa2c0ab387d7000de1ad793087686c88c6aa09, height 72)
	fullblocks_test.go:47: Testing block bm72 (hash 0d072d99f0410cae5e710dafc71f5ce988dbb7e1fa49d9cc0d2cbfe2a34a09aa, height 73)
	fullblocks_test.go:47: Testing block bm73 (hash 0a4bba8482704d4a788bfbe5fb9a6a626781b92f625b553ae302645a03c153e2, height 74)
	fullblocks_test.go:47: Testing block bm74 (hash 06cb2ffaf7e786cd9444d22fac469f3259bef0ecb3e1684798d6129212bb56ef, height 75)
	fullblocks_test.go:47: Testing block bm75 (hash 0784271b602329a01a805473108414c87c3b88f734de9e8aaa1590b8b8d17305, height 76)
	fullblocks_test.go:47: Testing block bm76 (hash 086a66a769810607e50f73f6a86dd368e5f1aaeb2ec798883360ba0a295c0660, height 77)
	fullblocks_test.go:47: Testing block bm77 (hash 0a3173e9d7e8ddd566930f992a4ae38ecb2a1d8e5f910a873496ce5d99cf6b64, height 78)
	fullblocks_test.go:47: Testing block bm78 (hash 0d04c76bb0ab88e5acfa5e28bd19f01632d4aacf8104c43302721d3ea1b4cb91, height 79)
	fullblocks_test.go:47: Testing block bm79 (hash 084f4f5480185619ccd0176f226bc8b8d8fd2264ceb9858984c78359e0cd8b8f, height 80)
	fullblocks_test.go:47: Testing block bm80 (hash 0063e250fc9c6bc1460311c2a1b36478ab4c5915c5f93ab6ad49fd115f241072, height 81)
	fullblocks_test.go:47: Testing block bm81 (hash 0d68a2cd5075f65b71d87611485805bad295359c1881dd5ef9608738a9947dfb, height 82)
	fullblocks_test.go:47: Testing block bm82 (hash 0326f59c2728bf1653ed805c16c32f74b4b34b2a88a19094bf297d31f1266552, height 83)
	fullblocks_test.go:47: Testing block bm83 (hash 018dd7c1328a621211ee48e52e26e576835d1a8fed866bd838472ee8a0694ea5, height 84)
	fullblocks_test.go:47: Testing block bm84 (hash 0d6a8c7146374c3983b3c2bf7c36eb354259ea9139570b06f2f5c30354a2c310, height 85)
	fullblocks_test.go:47: Testing block bm85 (hash 055b9899614db62bb1ba157f29404962b76cf67db9df666b61ad2626277d4df4, height 86)
	fullblocks_test.go:47: Testing block bm86 (hash 04cf4cbf55d8f0cc8c916d4d3bd2c35cba2f0855a4c6168313fba125e1bc7509, height 87)
	fullblocks_test.go:47: Testing block bm87 (hash 09651a3543ac5512adbeb1f0bc5a7d1ae7578ef9389c6439efa48936f506d0ab, height 88)
	fullblocks_test.go:47: Testing block bm88 (hash 07f676397d3be76ac668ebd65cff50d101cf0cb0690f860a308ec715f1492b15, height 89)
	fullblocks_test.go:47: Testing block bm89 (hash 06e004c785e2aed0f47e05c3541e37f08f478558faaf2da60893f36d74a99f9b, height 90)
	fullblocks_test.go:47: Testing block bm90 (hash 0c4b9a72edcb0faece2ecbb0374f4bcbf7e16c17371b1c2a18041a69c6b85a75, height 91)
	fullblocks_test.go:47: Testing block bm91 (hash 08c42e1c4a914486c13d7dd39948cb60c03eadac3d6d19077ebd7b6d21f18c74, height 92)
	fullblocks_test.go:47: Testing block bm92 (hash 04c0ac622224c534e690d036fc78c2b49cf4121cb15fe96e56d0df06d220ff05, height 93)
	fullblocks_test.go:47: Testing block bm93 (hash 077b996bdbccd366702abd20b00e7d1613b7a4e8083e17df46ff3b7959c31c7c, height 94)
	fullblocks_test.go:47: Testing block bm94 (hash 019458797b8c693058b344db46ba68a4bf9a5a560f46967194c9fa1df9f001fa, height 95)
	fullblocks_test.go:47: Testing block bm95 (hash 0647ecf7eeb133562a18ec83e86614a7bada114f569f1de3f4c55ddc8b33935a, height 96)
	fullblocks_test.go:47: Testing block bm96 (hash 0303da85145539463e7e7b0ebcd71e6bcc11dd102731bae52ba69d9f8657c194, height 97)
	fullblocks_test.go:47: Testing block bm97 (hash 0cc3a521bc2da919968b6e097c79d203336312471f7eaf7118c77b4cb3622bb7, height 98)
	fullblocks_test.go:47: Testing block bm98 (hash 0cce1f1285238504b3052e0df9c2a7e7bd03e392cc1f3a2f646a1eb9cf098cfc, height 99)
	fullblocks_test.go:47: Testing block bm99 (hash 0037a9679be69e72bb4dfbbb638a9f76c833a10d0db4afcaf75a53ed4a761c95, height 100)
	fullblocks_test.go:47: Testing block b1 (hash 011d6327b353e5e802716f65311f359d2b22bbe8dcae2bbd594c585558430080, height 101)
	fullblocks_test.go:130: Testing block b2 (hash 0e5fca7a3722eb9a5488760f7b87deb650fecdff9748537efd0ad26f04cf868d, height 102)
	fullblocks_test.go:47: Testing block b3 (hash 02933a6ddc55d42ad696bcfa6f4212718248cbbc22eeb34c3d0fd6ae6c95d84e, height 102)
	fullblocks_test.go:47: Testing block b4 (hash 03bb8487ba17ca23eb6208cc7ceb4676a144699a0be151b66f48ebbee9a51050, height 103)
	fullblocks_test.go:47: Testing block b5 (hash 05c8eec1634ba724ce1e532db523d71bec48415c293f118ece46f003b7cff3c8, height 104)
	fullblocks_test.go:47: Testing block b6 (hash 007659fb74d7d711015b0799591bceedaba15267d111d60e0948bfdf973ddbe6, height 105)
	fullblocks_test.go:47: Testing block b7 (hash 05574f81ca8539c005d476dc45a7554d610387bb7f7d6a08e5775dd2fde15978, height 105)
	fullblocks_test.go:215: Testing tip for block b6 (hash 007659fb74d7d711015b0799591bceedaba15267d111d60e0948bfdf973ddbe6, height 105)
	fullblocks_test.go:47: Testing block b8 (hash 0c418346b186bf9c4fa64a67a132887c1a8584a58cfe16e9b6d9e04de51fd362, height 106)
	fullblocks_test.go:47: Testing block b9 (hash 0d03193b486ca93fcb285c05338fdf460879a6c7fb88b647b3997a8c081f0bd6, height 107)
	fullblocks_test.go:47: Testing block b10 (hash 0e57fa632bbd71cc91840b108e7a39f6b850ca69adad6c224975cde9963979ad, height 108)
	fullblocks_test.go:47: Testing block b11 (hash 0ea3d9cecc96ae87d633dcb5a6317b6281b166e94f0c71771740375f3818a221, height 109)
	fullblocks_test.go:47: Testing block b12 (hash 0593c2088782d737f029757f0754fd4f08383d38f9a861d87fe37cbb405cc716, height 110)
	fullblocks_test.go:47: Testing block b13 (hash 0a46e89ad80b5e9edc73eed7456167b782acc6a6621203830ad0584955e238ab, height 111)
	fullblocks_test.go:47: Testing block b14 (hash 0a0e6b30b0385d986f625fb2b79f41f788ab1cf2b0bb374c3d26dadd318cf03c, height 111)
	fullblocks_test.go:215: Testing tip for block b13 (hash 0a46e89ad80b5e9edc73eed7456167b782acc6a6621203830ad0584955e238ab, height 111)
	fullblocks_test.go:47: Testing block b15 (hash 0181060be885843859e91cbadb17ba81f18f6bfb892356414f62565744412ddb, height 112)
	fullblocks_test.go:47: Testing block b16 (hash 0073257b718cc4226a0e48b04c8f237511dfd409e3afa3da1263dda2c6885656, height 113)
	fullblocks_test.go:130: Testing block b17 (hash 02a2376e64be52a9b0488127b39fe431a4b1cd8d18c5bff1108f4e0b2bcae5b1, height 114)
	fullblocks_test.go:47: Testing block b18 (hash 031ca95289bd99428d7d7142ef61f71337df19a16847dfb0cece144bce8649a0, height 114)
	fullblocks_test.go:47: Testing block b19 (hash 0dbd8db1249ef3a0a8db872c9c55abe44cb14b3e596f8f4e0c052d7af8b41d85, height 115)
	fullblocks_test.go:47: Testing block b20 (hash 0ea2ace450d0749f06c3c56939700eb4cfc59addd9f5ac51e12b884bdd49b243, height 116)
	fullblocks_test.go:47: Testing block b21 (hash 07dd5918a4e8f6ba67853fa87d03400c06a9ec9e66cef27e457d86b705a7bea5, height 117)
	fullblocks_test.go:47: Testing block b22 (hash 0387c34ba0cf8c40be57f76e4d7419dab0e324565e8c7b09f940367e38f1b070, height 118)
	fullblocks_test.go:47: Testing block b23 (hash 00654960275735777104d939cebebf6c9656f79db04bd6f6fb9ff356e78a3b05, height 119)
	fullblocks_test.go:47: Testing block b24 (hash 02293ae329dbb311cfbcd0a12cf732812082dd255d2f8b3cd02ec7273b40e566, height 119)
	fullblocks_test.go:215: Testing tip for block b23 (hash 00654960275735777104d939cebebf6c9656f79db04bd6f6fb9ff356e78a3b05, height 119)
	fullblocks_test.go:47: Testing block b25 (hash 04261823f7c36ccc7170067faeaaa3f7a2e6901f6c5d0dfafd8f2653efd4ffde, height 120)
	fullblocks_test.go:47: Testing block b26 (hash 04047129b12bf109c1a124850afbb77b133db4a48b8a5486f75fd858d24dcaa1, height 120)
	fullblocks_test.go:215: Testing tip for block b25 (hash 04261823f7c36ccc7170067faeaaa3f7a2e6901f6c5d0dfafd8f2653efd4ffde, height 120)
	fullblocks_test.go:47: Testing block b27 (hash 00288060f357555fdfabe48fc4a81d838b76d7deea54d5fc9f0cbe752e8efd15, height 121)
	fullblocks_test.go:47: Testing block b28 (hash 000010dc7c25044524a6844b5e3fd15e4591c5e77f7004379a05786710957ea4, height 121)
	fullblocks_test.go:215: Testing tip for block b27 (hash 00288060f357555fdfabe48fc4a81d838b76d7deea54d5fc9f0cbe752e8efd15, height 121)
	fullblocks_test.go:130: Testing block b29 (hash 0584b135d34f50cff28a6fdb721387cd940d717d114dcdf2dd3dca44f4093efb, height 122)
	fullblocks_test.go:130: Testing block b30 (hash 05254315b61ee6b137fe3e386237a2141f1b19643d1c29bb0b5e321d1a3c1c6c, height 122)
	fullblocks_test.go:130: Testing block b31 (hash 04395947617f09d16c5c4cc42d4384a1c0b6010ef1190a41201da656a282bc45, height 122)
=== RUN   TestMedianTime
--- PASS: TestMedianTime (0.00s)
=== RUN   TestMerkle
--- PASS: TestMerkle (0.00s)
=== RUN   TestTimeSorter
--- PASS: TestTimeSorter (0.00s)
=== RUN   TestCalcBlockSubsidy
--- PASS: TestCalcBlockSubsidy (0.00s)
=== RUN   TestSequenceLocksActive
--- PASS: TestSequenceLocksActive (0.00s)
	validate_test.go:69: Running 6 sequence locks tests
=== RUN   TestCheckConnectBlock
--- PASS: TestCheckConnectBlock (0.01s)
=== RUN   TestCheckBlockSanity
--- PASS: TestCheckBlockSanity (0.00s)
=== RUN   TestCheckTransactionSanity
--- PASS: TestCheckTransactionSanity (0.00s)
=== RUN   TestCheckTransactionOutputs
--- PASS: TestCheckTransactionOutputs (0.01s)
=== RUN   TestCheckTransactionInputs
--- PASS: TestCheckTransactionInputs (0.00s)
--- PASS: TestBestChainStateDeserializeErrors (0.00s)
--- PASS: TestTxOutCompressionErrors (0.00s)
--- PASS: TestStxoSerialization (0.00s)
--- PASS: TestCompressedTxOut (0.00s)
--- PASS: TestAmountCompression (0.00s)
--- PASS: TestScriptCompressionErrors (0.00s)
--- PASS: TestKeySetSerialization (0.00s)
--- PASS: TestBestChainStateSerialization (0.00s)
--- PASS: TestUtxoEntryDeserializeErrors (0.00s)
--- PASS: TestUtxoEntryHeaderCodeErrors (0.00s)
--- PASS: TestUtxoSerialization (0.00s)
--- PASS: TestSpendJournalErrors (0.00s)
--- PASS: TestSpendJournalSerialization (0.00s)
--- PASS: TestStxoDecodeErrors (0.00s)
--- PASS: TestVLQ (0.00s)
--- PASS: TestScriptCompression (0.00s)
=== RUN   ExampleBlockChain_ProcessBlock
--- PASS: ExampleBlockChain_ProcessBlock (0.01s)
=== RUN   ExampleCompactToBig
--- PASS: ExampleCompactToBig (0.00s)
=== RUN   ExampleBigToCompact
--- PASS: ExampleBigToCompact (0.00s)
PASS
ok  	github.com/bitgo/prova/blockchain	0.291s
```

**Comment by spencerlievens** [comment]
Bump @alexbosworth get this merged ;)

**Comment by jlopp** [comment]
Hm, the build passed but I'm not seeing any output from tests running https://travis-ci.org/BitGo/prova/jobs/308462544

**Comment by spencerlievens** [comment]
@jlopp - https://api.travis-ci.org/jobs/308462544/log.txt?deansi=true

You need to click on raw log and you will see the output.

**Pull request merged**
