### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by pd93**
This is a PR to add Docker support to the repository.

**Key Features:**
- Built on Alpine Linux (lightweight image)
- Includes Golang 1.x (latest) - v1.9 at time of commit
- Includes Git (used for `go get` commands)
- `docker-compose.yml` file for easy image handling
- Support for mounting a Prova configuration file

**Note:** I decided to use the `COPY` command instead of the `git clone` suggested in issue #32, because it allows the developer to build the image with the repository in its 'current state' rather than building from the latest commit to master.

For more details, see the comments in the files below.

### CODE REVIEW

**Comment by spencerlievens** [comment]
utACK

**Comment by pd93** [comment]
I've done quite a bit of testing with this now and it seems to work consistently on Docker for Windows and Debian. I don't currently have the ability to test on OSX.

In order to enable the config file mounting, you will need to create `/prova.conf` and `/provactl.conf` in the root of the project with your configuration (I considered putting these in a `/config` folder, but saw the existing `/chaincfg` and didn't want to confuse things). You will then need to uncomment the volume mounts in the `/docker-compose.yml` file. This will load them into the correct location when the container is brought up. As they are mounted, changes on the host will mirror to the container in real-time.

**Note:** As this method requires users to create non-committed config files in the project root (which then make your workspace 'dirty'), I would suggest that we also add the config files to the `.gitignore`. Obviously the sample config is still needed, so perhaps something like:
```
# Config files
/prova.conf
/provactl.conf
```
Any thoughts on this are welcome. I'll continue to work with Oscar to make sure this works fully

**Comment by pd93** [comment]
One problem that we did find, is that we don't appear to be able to bind the RPC listener to an IPv6 port. 

A warning is displayed during startup:
```
14:54:56 2017-11-30 [WRN] RPCS: Can't listen on [::1]:18334: listen tcp6 [::1]:18334: bind: cannot assign requested address
14:54:56 2017-11-30 [INF] RPCS: RPC server listening on 127.0.0.1:18334
```

The connection via ipv4 seems to work fine. I suspect this might be an Alpine issue as it's such a stripped down version of Linux. It's possible that reverting to a `debian-slim` image or similar could fix the issue, but I'd prefer to get Alpine working if I can - purely for it's efficiency.

**Comment by Duality-CDOO** [comment]
@pd93 did you have any joy with Alpine and IPv6?

**Comment by pd93** [comment]
@Duality-CDOO Haven't had the chance to test this any further unfortunately, so the IPv6 error is still there. However, we've been using it without issue over IPv4. I might have some time to pick this up again towards the end of the week - I'll see if I can get it working then.

**Pull request closed without merging**
